Update web implementation to depend on Dart 3.3 JS interop + the recommended `web` package
fluttercommunity/wakelock_plus pull request #26
Opened 2024-02-29 15:28 UTC by davidmartos96

Fixes #24 

The following PR updates de Web code to depend on the enhanced JS interop solution Dart provided in version 3.3+
The `js` dependency and `dart:html` are dropped in favor of `web` and `dart:js_interop` https://dart.dev/interop/js-interop
Migration: https://dart.dev/interop/js-interop/package-web

This seems to be the approach the official plugins are starting to take for the web implementation

2024-03-07 15:18 UTC, davidmartos96 commented
For some strange reason the CI is failing to start the iOS Simulator. Doesn't seem to be anything related to the PR changes, but it worked correctly for a previous run 2 weeks ago.

2024-03-19 13:40 UTC, diegotori requested changes

2024-03-19 13:57 UTC, davidmartos96 commented on wakelock_plus/pubspec.yaml
> +  flutter: ">=3.19.0"
I'll check later, although my understanding is that it's only available from Dart version 3.3.
In fact, the pub.dev `web` package has 3.3 as a constraint, and it's what the team is starting to push forward to be compatible with WASM.

2024-03-21 21:49 UTC, vbuberen commented on wakelock_plus/pubspec.yaml
> +  flutter: ">=3.19.0"
Yes, `js_interop` is available only since Dart 3.3 https://medium.com/dartlang/dart-3-3-325bf2bf6c13, so there is no way to have older versions supported.

2024-03-21 21:51 UTC, diegotori commented on wakelock_plus/pubspec.yaml
> +  flutter: ">=3.19.0"
Understood.

When I get back on Monday, I think we'll have to make this a major version so that it's distinct from everything up to this point.

`chewie` will also have to be bumped up due to this, since it makes use of this library.

2024-03-21 22:10 UTC, vbuberen commented on wakelock_plus/pubspec.yaml
> +  flutter: ">=3.19.0"
Sorry for adding some work. Had users requesting to support WASM and agreed to do the migration.

2024-03-25 21:50 UTC, diegotori commented
@davidmartos96 please re-sync your changes with `main`'s latest ones. Thanks.

2024-03-25 21:59 UTC, vbuberen commented
@diegotori I think you can turn on this option in the repo to get a button to do such syncs yourself.
Check `General` section of repository settings and find options `Always suggest updating pull request branches`:
<img width="799" alt="Screenshot 2024-03-25 at 23 57 47" src="https://github.com/fluttercommunity/wakelock_plus/assets/13467769/177a7267-f7a8-4a42-8b23-f160f7c0d9dd">

2024-03-25 22:05 UTC, davidmartos96 commented
> @diegotori I think you can turn on this option in the repo to get a button to do such syncs yourself as well.
> Check `General` section of repository settings and find options `Always suggest updating pull request branches`:
> <img width="799" alt="Screenshot 2024-03-25 at 23 57 47" src="https://github.com/fluttercommunity/wakelock_plus/assets/13467769/177a7267-f7a8-4a42-8b23-f160f7c0d9dd">
> 

I didn't know that was an option in the repo. I was confused that the option to update with master wasn't there.

2024-03-26 16:32 UTC, diegotori commented
LGTM.

2024-03-26 16:33 UTC, diegotori approved these changes

2024-03-26 16:33 UTC, merged