chore(deps): Allow web ^1.0.0
fluttercommunity/wakelock_plus pull request #70
Opened 2024-08-11 16:37 UTC by provokateurin

## Description

Allows web ^1.0.0 without any breaking changes as the used API elements did not change since ^0.5.1.

Closes https://github.com/fluttercommunity/wakelock_plus/issues/68

2024-08-11 16:39 UTC, provokateurin commented
After merging please also make a new release soon, so other packages depending on web ^1.0.0 can finally be upgraded.

2024-08-11 16:40 UTC, diegotori requested changes

2024-08-11 16:40 UTC, diegotori commented on wakelock_plus/pubspec.yaml
> +version: 1.2.8
@provokateurin Thanks for your contribution. 

Please revert the pubspec and changelog changes (if any).

I'll release it when your changes pass automation and are merged, at most by tomorrow.

2024-08-11 16:42 UTC, provokateurin commented on wakelock_plus/pubspec.yaml
> +version: 1.2.8
Done!

2024-08-12 01:44 UTC, diegotori approved these changes
LGTM.

2024-08-12 01:44 UTC, merged