Add Swift Package Manager support
fluttercommunity/wakelock_plus pull request #72
Opened 2024-08-12 17:02 UTC by charafau

Swift Package Manager is supported by flutter so I updated this plugin to support this as well - based on https://docs.flutter.dev/packages-and-plugins/swift-package-manager/for-plugin-authors

- Swift package manager support
- bump min ios version to 12
- bump min macos version to 10.14
- bump android min sdk to 21 in example
- update pigeon to 21.2 (bug fix for spm)
- update git ignore

2024-08-12 17:06 UTC, diegotori commented
@charafau also, please revert the `pigeon` related changes, since they'll be addressed in another PR, which will target `wakelock_plus_platform_interface`.

2024-08-12 17:07 UTC, diegotori requested changes

2024-08-12 17:07 UTC, diegotori commented on wakelock_plus/ios/wakelock_plus/Sources/wakelock_plus/WakelockPlusPlugin.m
> +#import "./include/wakelock_plus/UIApplication+idleTimerLock.h"
Why are we changing the source paths? Can this be accomplished without having to do this?

2024-08-12 17:17 UTC, diegotori commented
@charafau I'm gonna submit a PR shortly that upgrades `pigeon` to `21.2` so that `wakelock_plus_platform_interface` is upgraded before your changes.

2024-08-12 17:50 UTC, diegotori commented
@charafau because this requires switch Flutter to the `main` channel, I'm gonna hold off on approving this PR.

Once the Flutter team releases SPM support in the `stable` channel, then I'll revisit your PR.

Once again, thanks for your contribution.

2024-08-13 02:33 UTC, charafau commented on wakelock_plus/ios/wakelock_plus/Sources/wakelock_plus/WakelockPlusPlugin.m
> +#import "./include/wakelock_plus/UIApplication+idleTimerLock.h"
According to the docs, public headers should be added to `include` path

2024-08-13 02:34 UTC, charafau commented
> Once the Flutter team releases SPM support in the `stable` channel, then I'll revisit your PR.

Ok, I think we might prepare support for SPM before that though. Let me know, I will probably add support for more community packages. Closing this for now then

2024-08-13 02:34 UTC, closed without merging

2024-08-13 02:35 UTC, diegotori commented on wakelock_plus/ios/wakelock_plus/Sources/wakelock_plus/WakelockPlusPlugin.m
> +#import "./include/wakelock_plus/UIApplication+idleTimerLock.h"
Understood. Nevertheless, I'm gonna hold off on this PR until the Flutter team finalizes SPM support.

2024-08-13 02:37 UTC, diegotori commented
> > Once the Flutter team releases SPM support in the `stable` channel, then I'll revisit your PR.
> 
> Ok, I think we might prepare support for SPM before that though. Let me know, I will probably add support for more community packages. Closing this for now then

Totally get where you're coming from. However, I also have to weigh your changes against something that is currently non-final and subject to change. 

Otherwise, we would be doing twice the work if the Flutter team changes the SPM integration between now and when it goes stable.

2024-08-13 03:29 UTC, SputNikPlop commented
Another idea to consider would be having a beta branch since this will reach the beta branch of flutter soon