fix: resolve symbol conflicts in wakelock_plus by updating Pigeon prefix
fluttercommunity/wakelock_plus pull request #82
Opened 2024-12-20 21:56 UTC by weitsai

Updated the Pigeon configuration for wakelock_plus to use a unique ObjCOptions.prefix ("WKP") to prevent symbol conflicts with other plugins such as image_picker_ios.

Changes include:
- Modified the Pigeon prefix from "FLT" to "WAKELOCK" in `messages.dart`.
- Regenerated the Pigeon files to reflect the new prefix.
- Cleaned and rebuilt the project to ensure compatibility.

## Description

*A clear and concise description of what your PR accomplishes.*

2024-12-20 21:57 UTC, diegotori requested changes

2024-12-20 21:57 UTC, diegotori commented on wakelock_plus/pigeons/messages.dart
> +    prefix: 'WAKELOCK',
Change this to `WAKELOCKPLUS`.

2024-12-21 00:04 UTC, weitsai commented on wakelock_plus/pigeons/messages.dart
> +    prefix: 'WAKELOCK',
Changed to `WAKELOCKPLUS`.

2024-12-21 00:05 UTC, diegotori approved these changes
LGTM

2024-12-21 00:05 UTC, diegotori commented
@weitsai Thanks for your contribution. Once the automation goes green, then I'll release a new build.

2024-12-21 00:07 UTC, weitsai commented
> @weitsai Thanks for your contribution. Once the automation goes green, then I'll release a new build.

Thanks for the update! I'll wait for the automation to complete. Let me know if there's anything else I can assist with.

2024-12-21 00:28 UTC, diegotori commented
@weitsai I'm taking over your PR to the finish line, mainly to regenerate the Pigeons.

2024-12-21 00:35 UTC, weitsai commented
Ok, thanks!

2024-12-21 03:07 UTC, merged

2024-12-21 03:20 UTC, diegotori commented
@weitsai deployed as `wakelock_plus` and `wakelock_plus_platform_interface`, versions `1.2.10` and `1.2.2` respectively.